#!/bin/sh
#
# Copyright (c) 2025, Carnegie Mellon University.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
# WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

#
# mkmloghdr.sh  generate custom mlog wrapper header
# 24-May-2025  chuck@ece.cmu.edu
#

#
# configuration:
#
# [1] facility names (format: SHORT or SHORT:LONG) -- LONG is optional.
#     the first entry is normally generic MLOG
#
facs="MLOG MVP FBUF FDIO MPI QUE"

#
# [2] optional #define alias for DBG[0-3] channels
#
dbg0=
dbg1=
dbg2=
dbg3=

#
# [3] optional: update/replace below license and include of mlog.h as needed
#
cat<<EOD
/*
 * Copyright (c) 2025, Carnegie Mellon University.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
 * HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * DO NOT EDIT -- THIS FILE GENERATED BY mkmloghdr.sh
 */
#ifndef _MKMLOGHDR_SH_
#define _MKMLOGHDR_SH_

#include "mlog.h"

EOD

#
# end of configurations
#

#
# generate facility name arrays
#
cat<<EOD
#ifdef MKMLOGHDR_DEF_FNAMES

struct mkmloghdr_def_facnames {
    char *sname;
    char *lname;
};

static struct mkmloghdr_def_facnames mkmloghdr_facdef[] = {
EOD

for fspec in $facs
do
    short=`echo $fspec | sed -e s/:.*//`
    long=`echo $fspec | sed -e s/^.*://`
    if [ $short = $long ]; then
        echo "    { \"${short}\", 0 },"
    else
        echo "    { \"${short}\", \"${long}\" },"
    fi
done

cat<<EOD
    { 0, 0 }
};

#endif /* MKMLOGHDR_DEF_FNAMES */

EOD

#
# generate facility levels
#
count=0
for fspec in $facs
do
    short=`echo $fspec | sed -e s/:.*//`
    n=${count}
    count=`expr ${count} + 1`
    if [ ${short} != "MLOG" ]; then  # skip generic MLOG facility

cat<<EOD
/*
 * level defines for ${short} facility
 */
#define ${short}_MLOG ${n}
#define ${short}_EMERG (MLOG_EMERG|${short}_MLOG)
#define ${short}_ALERT (MLOG_ALERT|${short}_MLOG)
#define ${short}_CRIT (MLOG_CRIT|${short}_MLOG)
#define ${short}_ERR (MLOG_ERR|${short}_MLOG)
#define ${short}_WARN (MLOG_WARN|${short}_MLOG)
#define ${short}_NOTE (MLOG_NOTE|${short}_MLOG)
#define ${short}_INFO (MLOG_INFO|${short}_MLOG)
#define ${short}_DBG (MLOG_DBG|${short}_MLOG)
#define ${short}_DBG0 (MLOG_DBG0|${short}_MLOG)
#define ${short}_DBG1 (MLOG_DBG1|${short}_MLOG)
#define ${short}_DBG2 (MLOG_DBG2|${short}_MLOG)
#define ${short}_DBG3 (MLOG_DBG3|${short}_MLOG)
EOD
        if [ "${dbg0}" != "" ]; then
            echo "#define ${short}_${dbg0} (MLOG_DBG0|${short}_MLOG)"
        fi
        if [ "${dbg1}" != "" ]; then
            echo "#define ${short}_${dbg1} (MLOG_DBG1|${short}_MLOG)"
        fi
        if [ "${dbg2}" != "" ]; then
            echo "#define ${short}_${dbg2} (MLOG_DBG2|${short}_MLOG)"
        fi
        if [ "${dbg3}" != "" ]; then
            echo "#define ${short}_${dbg3} (MLOG_DBG3|${short}_MLOG)"
        fi

        echo ""
    fi

done

cat<<EOD

#endif /* _MKMLOGHDR_SH_ */
EOD

exit 0
