#!/bin/sh
# prep-config.sh  prepare the directory used to supply configuration information
# to cloud-init in the mvpnet environment.
#
# 2025-06-18  crd@andrew.cmu.edu
#

die () {
  echo "FATAL: $*" 1>&2
  exit 1
}

warn () {
  echo "INFO: $*" 1>&2
}

usage () {
  if [ -n "$*" ]; then
    echo "error: $*"
  fi
  echo "prep-config - prepare a seed directory to supply minimal cloud-init"
  echo "              configuration in the mvpnet environment"
  echo
  echo "usage: prep-config seed-dir"
  echo
  exit 1
}

## parse args
[ $# -eq 0 ] && usage "no seed directory specified"
seed_dir="${1}"

# ok if seed_dir already exists
mkdir -p ${seed_dir} || die "failed to make seed directory"

# create a passwordless ssh keypair for the VMs if it doesn't already exist
if [ -s ${seed_dir}/id_ed25519 ]; then
  warn "using existing ssh key found in seed directory"
else
  warn "no ssh key found, generating a new one for you"
  ssh-keygen -q -f ${seed_dir}/id_ed25519 -P "" || die "couldn't generate ssh keys"
fi

# just put all the keys that are authorized for this system plus the newly
# generated mvpnet key into the guest instance
SSH_AUTHORIZED_KEYS=$(grep -sh "^ssh" ~/.ssh/authorized_keys ${seed_dir}/id_ed25519.pub|sed -e 's/^/    - /')

cat > ${seed_dir}/user-data << EOF || die "couldn't create user-data file"
#cloud-config
# DO NOT EDIT THIS FILE!!!
# IT IS GENERATED FROM prep-config.sh
#
bootcmd:
  - mount -oro /dev/disk/by-label/cidata /mnt
  - mount -oro -tmsdos /dev/msdosfs/cidata /mnt # freebsd version, ok to fail on linux
  - [ cloud-init-per, once, imageprep, sh, -c, '/mnt/imageprep.sh' ]
  - [ cloud-init-per, always, mvpnet-init, sh, -c, '/mnt/mvpnet-init' ]
user:
  name: ${USER}
  ssh_authorized_keys:
${SSH_AUTHORIZED_KEYS}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
# this appears to be necessary when hostname is set by systemd?
create_hostname_file: false
# there are certain things that need to happen after all of the other
# cloud-init stuff has finished.  run those from this script.
runcmd:
  - [ cloud-init-per, once, late, sh, -c, '/mnt/late.sh' ]
EOF

cat > ${seed_dir}/meta-data << EOF || die "couldn't create meta-data file"
instance-id: iid-local01
dsmode: local
EOF

# copy the other scripts that we need
for f in imageprep.sh mvpnet-init.sh proxy-config.sh install-packages.sh late.sh; do
  cp $(dirname ${0})/${f} ${seed_dir} || die "couldn't copy ${f} script to seed dir"
  chmod 755 ${seed_dir}/${f}
done

# rename since we're selecting the shell version
mv ${seed_dir}/mvpnet-init.sh ${seed_dir}/mvpnet-init

echo
echo "prep-config finished!"
echo
echo "place any other scripts or data that you want to be available"
echo "to the guest into ${seed_dir} before starting mvpnet."
echo

exit 0
