#!/bin/sh
# prep-config.sh  prepare the directory used to supply configuration information
# to cloud-init in the mvpnet environment.
#
# 2025-06-18  crd@andrew.cmu.edu
#

die () {
  echo "FATAL: $*" 1>&2
  exit 1
}

warn () {
  echo "INFO: $*" 1>&2
}

usage () {
  if [ -n "$*" ]; then
    echo "error: $*"
  fi
  echo "prep-config - prepare a directory to supply cloud-init configuration in"
  echo "              the mvpnet environment"
  echo
  echo "usage: prep-config seed-dir [packagelist]"
  echo
  echo "  seed-dir is the name of the target directory to write"
  echo "  configuration information"
  echo
  echo "  packagelist is an optional text file containing a list of"
  echo "  package names, one per line, to install after startup"
  echo
  exit 1
}

## parse args
[ $# -eq 0 ] && usage "no seed directory specified"
seed_dir="${1}"
if [ $# -eq 2 ]; then
  if [ -s ${2} ]; then
    PACKAGES="packages: [$(cat ${2} | xargs | tr ' ' ',')]"
  else
    die "couldn't read package list file"
  fi
  else
    warn "no packagelist file specified, not adding any packages to install"
fi

# ok if seed_dir already exists
mkdir -p ${seed_dir} || die "failed to make seed directory"

# create a passwordless ssh keypair for the VMs if it doesn't already exist
if [ -s ${seed_dir}/id_ed25519 ]; then
  warn "using existing ssh key found in seed directory"
else
  warn "no ssh key found, generating a new one for you"
  ssh-keygen -q -f ${seed_dir}/id_ed25519 -P "" || die "couldn't generate ssh keys"
fi

# just put all the keys that are authorized for this system plus the newly
# generated mvpnet key into the guest instance
SSH_AUTHORIZED_KEYS=$(grep -sh "^ssh" ~/.ssh/authorized_keys ${seed_dir}/id_ed25519.pub|sed -e 's/^/    - /')

cat > ${seed_dir}/user-data << EOF || die "couldn't create user-data file"
#cloud-config
# DO NOT EDIT THIS FILE!!!
# IT IS GENERATED FROM prep-config.sh
#
bootcmd:
  - mount -oro /dev/disk/by-label/cidata /mnt
  - [ cloud-init-per, once, imageprep, sh, -c, '/mnt/imageprep.sh' ]
  - [ cloud-init-per, always, mvpnet-init, sh, -c, '/mnt/mvpnet-init' ]
user:
  name: ${USER}
  ssh_authorized_keys: 
${SSH_AUTHORIZED_KEYS}
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
${PACKAGES}
# this appears to be necessary when hostname is set by systemd?
create_hostname_file: false
EOF

cat > ${seed_dir}/meta-data << EOF || die "couldn't create meta-data file"
instance-id: iid-local01
dsmode: local
EOF

echo
echo "prep-config finished!"

exit 0
